pipeline{
    node any

    environment{
        JAVA_HOME = "C:\\Program Files\\Java\\jdk-17"
        PATH = "${env.JAVA_HOME}\\bin;${env.PATH}"
    }

    stages{
        stage("Repo Clone"){
            steps{
                git branch:'main',
                credentialsId: 'github-creds',
                url: 'https://github.com/ShivrajTheCoder/HelloJavaApi.git'
            }
        }
        stage('Check Java'){
            steps{
                bat 'echo JAVA_HOME=%JAVA_HOME%'    
                bat 'java -version'
            }
        }
        stage("Build"){
                bat "mvn clean package"    
        }
        post{
            success{
                echo "Build Successfull"
            }
            failure{
                echo "Build Failed"
            }
        }
}
