pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        JAVA_HOME = "C:\\Program Files\\Java\\jdk-17"
        PATH = "${env.JAVA_HOME}\\bin;${env.PATH}"
    }

    stages {
        stage('Clone Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/ShivrajTheCoder/HelloJavaApi.git'
            }
        }

        stage('Build JAR') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t hello-java-app .'
            }
        }

        stage('Stop Old Container') {
            steps {
                bat 'docker stop my-java-app || exit 0'
                bat 'docker rm my-java-app || exit 0'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d --name my-java-app -p 8080:8080 hello-java-app'
            }
        }
    }

    post {
        success {
            echo 'App Deployed via Docker 🚀'
        }
        failure {
            echo 'Pipeline Failed ❌'
        }
    }
}